### PR TITLE
Replace std::[u]int* with [u]int*, cstdint with stdint.h.

### PR DESCRIPTION
**Pull request by jaykrell**
This is believed to be more portable, but there are other ways.

### CODE REVIEW

**Comment by jaykrell** [comment]
Oops, now I see the comment about use_c_headers branch. So this is probably moot.

**Comment by jaykrell** [comment]
This represents a possible alternative to part of what you did.
It is possible that a newer Microsoft UCRT already or soon will help here.
That this stuff was or will be factored out, and become therefore usable in kernel mode. (I've been working multiple angles here, sorry).

**Comment by jaykrell** [comment]
https://github.com/dcleblanc/SafeInt/issues/22

**Comment by dcleblanc** [comment]
Fixed in branch

**Pull request closed without merging**
