### PR TITLE
Add CMake files, set up Travis/AppVeyor CI

### PR DESCRIPTION
**Pull request by egor-tensin**
This is more of an invitation for a discussion rather than a proper pull request really. I was interested in using SafeInt in my projects, some of which support VS 2013 through 2019. So I wanted to make sure it works with all the target compilers. I set up CI pipelines on AppVeyor (for VS) at https://ci.appveyor.com/project/egor-tensin/safeint and Travis (for GCC/clang) at https://travis-ci.com/github/egor-tensin/SafeInt, and found that the bundled tests don't really work on some versions. In addition, I added CMake files to make integration with CMake-based projects easier (admittedly, it's not really necessary for a single-header library), but it also makes building the tests platform-agnostic, which I thought was nice. So I guess I wanted to ask a number of questions really:

1. Would you be interested in merging the CMake files? Makes the directories (i.e. GccTest/, ClangTest/, SafeIntTest/, etc.) in Test/ unnecessary.
2. Would you be interested in adding the CI pipelines to your repository? It pretty much costs nothing, except you have to wait sometimes for the AppVeyor builds to finish. I'm willing to add more use cases to the pipelines (like, w/ the exceptions being disabled completely, etc.).
3. Would you be interested in supporting older compilers? I'm more interested in VS 2013/2015, but it can also be made to work with clang 3.3-3.5, gcc 4.6-4.9, etc.

Now, for the specific CI failures. On AppVeyor, the tests fail on VS 2013/2015 due to (I think) `__cpp_exceptions` being undefined and `SafeIntDefaultExceptionHandler` getting assigned `InvalidParameterExceptionHandler` instead of `CPlusPlusExceptionHandler`. Same goes for clang 3.5 & GCC 4.9 on Travis. GCC 4.4 doesn't support `noexcept`, which is why this test case can be thrown away, but it can be made to work if `noexcept` is made optional.

### CODE REVIEW

**Comment by dcleblanc** [comment]
First of all, yes, I would like to add CMake support. I'm not very good at CMake, but I do want to get more up to speed on it. Though a question I do have is I do still want compiler-specific tests - for example, I build and test in Visual Studio on Windows, but test gcc and clang both on Linux. So if CMake just built one or the other, I'm missing coverage. A user probably wants to just test with whatever compiler they will use, but I have to cover all the supported compilers (though I only sporadically test the Intel compiler).

I do want to support older compilers to the extent that I can, and there's a good bit of code that makes accommodations for older compilers. That said, I don't have an easy way to maintain a bunch of different versions of say Visual Studio, so it gets hard to test. If there's a way to make that work easily, I'd be very interested.

That said, I think practically, we do need C++11 support or better now, and requiring a 9 year old standard doesn't seem too onerous. But it might work with older compilers - the catch is that if you have a modern runtime library install, the library requires C++11, so I can't test this with a decade old compiler. It would be good to know if I'm breaking those folks, though.

We really can't do the runtime tests without a C++ exception class - all sorts of problems occur. The code is written to assume that the exception functions never return. The only thing I can suggest there is to take the tests that are in place for the non-throwing methods, and just run those if there's no exception support. That wouldn't catch a bug where I'd failed to maintain the exception specialization and the non-throwing code identically, but it would give you a lot of coverage.

As you likely noticed, I just added support for compiling with noexcept, so it is very possible that there could be some follow-on work needed.

**Comment by egor-tensin** [comment]
> So if CMake just built one or the other, I'm missing coverage.

I've updated the CMake files to support all the build options in the Makefiles and VS project files. Namely:

* `-Wall` on GCC and clang and `/W4` on MSVC,
* There's now an option to turn on sanitization (`SAFEINT_SANITIZE`), which adds `-ftrapv -fsanitize=undefined`.
* There's now an option to disable exceptions (`SAFEINT_NO_EXCEPTIONS`), which adds `-fno-exceptions`.

You can use on Linux like this:

    mkdir build && cd build
    cmake -D CMAKE_BUILD_TYPE=Release -D SAFEINT_SANITIZE=ON /path/to/working/copy/SafeInt
    cmake --build .

On Windows, CMake generates multi-configuration build files, which means there's no `CMAKE_BUILD_TYPE` parameters.

    mkdir build
    cd build
    cmake -G "Visual Studio 15 2017" -A x64 /path/to/working/copy/SafeInt
    cmake --build . --config Debug

This is exactly what's being done on Travis for GCC and Clang on Linux (see .travis.yml) and on AppVeyor for VS on Windows (see .appveyor.yml), albeit it's a bit cluttered due to limitations of YAML syntax.

You can even move all the warning pragmas out of the source files to the corresponding CMakeLists.txt so that they don't mess with user-defined options.

**Comment by egor-tensin** [comment]
> That said, I think practically, we do need C++11 support or better now, and requiring a 9 year old standard doesn't seem too onerous.

The oldest GCC is now 4.7 on Travis. It's the first version to support `-std=c++11` & to set `__cplusplus` to the proper value. I think there's nothing that should stop the library to support this version, but the build fails due to `InvalidParameterExceptionHandler` getting selected instead of `CPlusPlusExceptionHandler` by default (and the runtime tests `abort()`). See https://travis-ci.com/github/egor-tensin/SafeInt/jobs/398298202.

Same goes for VS 2015 (https://ci.appveyor.com/project/egor-tensin/safeint/builds/35700128/job/w52h38h9eeg9ah8b).

**Comment by egor-tensin** [comment]
> If there's a way to make that work easily, I'd be very interested.

In fact, there is! AppVeyor has a very good support for multiple Visual Studio versions. I've set up a pipeline at https://ci.appveyor.com/project/egor-tensin/safeint. It reads .appveyor.yml and sets up build jobs and everything (currently there're some jobs queued). It now builds w/ every Visual Studio from 2013 onwards, both Debug & Release builds.

Same goes for testing multiple GCC & Clang versions, I used Travis for that, see https://travis-ci.com/github/egor-tensin/SafeInt. It uses .travis.yml in the repository in a similar manner.

The costs are pretty minimal, you need to set up 2 accounts (you can sign up using GitHub), and on AppVeyor you need to "create a project" first, while Travis does everything automatically on each commit.

**Comment by egor-tensin** [comment]
> As you likely noticed, I just added support for compiling with noexcept

You mean `SAFEINT_REMOVE_NOTHROW`? I haven't noticed that, thanks.

**Comment by egor-tensin** [comment]
So, in summary:

1. CMake files have been added for the project. Build files for the tests are unnecessary now. `SAFEINT_REMOVE_NOTHROW` is defined on VS prior to 2015 automatically.
2. Two CI pipelines have been set up to test the library against GCC 4.7 to 9 and Clang 3.5 to 11 on Linux (https://travis-ci.com/github/egor-tensin/SafeInt) and Visual Studio 2013 to 2019 on Windows (https://ci.appveyor.com/project/egor-tensin/safeint). Runtime tests are run automatically. Sanitization is turned on for Clang builds.
3. Runtime tests fail on GCC 4.*, Clang 3.5 and Visual Studio 2013/2015 due to the library calling `abort()` instead of throwing an exception (I think).

**Comment by dcleblanc** [comment]
It should compile on Visual Studio with -Wall, though they occasionally introduce new warnings and break that. But that's the goal.

I take it the old gcc is screwing up because:

#if __cpp_exceptions >= 199711L

isn't evaluating as we'd expect? 

What I should do is something like I did around line 85 sorting out constexpr support, allow the user to enforce what they want for older compilers.

You said:
> You mean SAFEINT_REMOVE_NOTHROW? I haven't noticed that, thanks.

No, what I meant was this, at line 717:
#if __cpp_exceptions >= 199711L

It was failing to compile, whether you used SafeIntExceptionHandler < SafeIntException > or not, when exceptions were disabled. The class obviously should have only been defined if you're possibly using it. Which I think is now causing problems with older compilers that might not be implementing the feature defines.

So, if the older compiler does allow compiling without exceptions, but won't tell me what it is doing, then that causes difficulties, but we should have a way to tell the code what it should do. Which I have for many things, for example constexpr - I'll try to sort it out, but you can force it.

What I think I should do about the tests aborting is just provide my own exception handler, and force it to use that, instead of taking what the defines give me. This doesn't solve the problem of trying to test without exceptions, but I'll intentionally exclude that for now. It is a bit of a puzzle how to provide a custom exception handler, and one of the things I have meant to do is create an example of this. I should also have a in-class option to throw something derived from std::exception, and that would be another way around that - the runtime tests could just compile with that forced on.

**Comment by dcleblanc** [comment]
I just created a cmake_test branch - could you please re-target this PR to that branch, and then I'll just take it there. As discussed above, there's a couple of things I ought to do to the core library file, and it would be easiest to have a branch we can just collaborate in.

**Comment by egor-tensin** [comment]
> I take it the old gcc is screwing up because:

Yes, it's undefined on GCC 4.*, clang <= 3.5 and VS 2013-2015, I just checked. See e.g. https://godbolt.org/z/f7jejM for GCC 5.1 vs https://godbolt.org/z/dsaGEW for GCC 4.9.

> No, what I meant was this, at line 717:

I see that now, thanks. But unless `SAFEINT_REMOVE_NOTHROW` is defined, other declarations would effectively use `noexcept`, e.g. `SafeInt_InvalidParameter` methods at line 746 and 752. Unless proper compiler version testing is used, there's no way to work around that I'm afraid, since there doesn't seem to be any nice feature macro for `noexcept`, like `__cpp_constexpr`. I'd be happy to help with that.

**Comment by egor-tensin** [comment]
> could you please re-target this PR to that branch

Done.

**Comment by dcleblanc** [comment]
I'm experienced at wrestling with compilers not really advertising what they do, but have not been good about keeping a library of them to test against. I'm grateful for your help in closing that gap. As you can see, just pushed a change that should help with -noexcept, and if there's other things we need to address, happy to fix those. It's been a while since I looked at the nothrow stuff - it is something @DanielJump requested a couple of years ago. We can likely sort out support for noexcept keyword with some combination of compiler version and language level support.

**Pull request merged**
