### PR TITLE
Remove references.

### PR DESCRIPTION
**Pull request by jaykrell**
Why were the used?
No difference?

### CODE REVIEW

**Comment by dcleblanc** [comment]
They were used back when x86 was common, and I wanted them to be efficiently passed as if they were pointers. Are they breaking something? If not, then we should leave them alone.

**Comment by jaykrell** [comment]
x86 I kinda figured. But note that x86 fastcall at least can pass one int64 by value in registers.
No they don't break anything, just kinda wonky and inefficient (including on x86 Unix which has a few parameters in registers too).

**Comment by dcleblanc** [comment]
Yes, and we have 3 of them per method. Plus, you can’t be sure that someone is using fastcall. The compiler will normally, especially on x64, inline all these completely out. I have some unknown large number of people across the industry using this class, so while I want to get it to where you can use it, if it isn’t broken, I want to be conservative with fixes, or it could get broken. I agree that on x64, const int64_t& and int64_t are going to work out to exactly the same thing, and if were writing it now, I might do it that way – but at the time, x86 was the norm. Unless the const reference is causing someone’s compiler to become annoyed, I don’t see anything but risk in touching it.

**Comment by jaykrell** [comment]
Some of the references are in amd64-specific code.

#if SAFEINT_USE_INTRINSICS
// As usual, unsigned is easy
inline bool IntrinsicMultiplyUint64( const std::uint64_t& a, const std::uint64_t& b, std::uint64_t* pRet ) SAFEINT_NOTHROW
{

**Comment by dcleblanc** [comment]
If it is not causing a bug, I see no need to make a change. If you can show me that it is emitting the wrong assembly, and it gets better if we change it, then I’ll make a change.

This is what I see in release:

00007FF7253B103E  mov         qword ptr [rsp+28h],rax
    SafeInt<uint64_t> s1 = 0x1234567890abcdull;
    uint64_t t = 0x800000000;
    s1 *= t;
00007FF7253B1043  mov         rcx,1234567890ABCDh
00007FF7253B104D  mov         qword ptr [rsp+20h],0
00007FF7253B1056  mov         rax,800000000h
00007FF7253B1060  mul         rax,rcx
00007FF7253B1063  test        rdx,rdx

I really don’t see any way for it to get any more efficient, and don’t think tidiness changes are going to help.

**Comment by dcleblanc** [comment]
Duplicate of other pull request

**Pull request closed without merging**
